FROM node:20

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

RUN rm -r node_modules/

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "build","-l","3000"]